### ISSUE TITLE
miniOrange SAML 2.0 SSO settings appear on group site dashboard

### ISSUE THREAD

**Issue by bree-z** [hard-g/openlab-bmcc#3]
Hi Boone, 

Not sure if this is a bug, but the settings for the SAML plugin are accessible on the dashboard of group sites.  

<img width="1232" alt="screen shot 2018-07-20 at 1 30 40 pm" src="https://user-images.githubusercontent.com/7189824/42997956-35e67590-8c21-11e8-96b2-b256b901294d.png">

**Comment by boonebgorges** [comment]
Yes, this feels like a bug. I've fixed it. Thanks!
